/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 20-jul.-2022 18:45:26 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_confirmados_laboratorio]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [confirmados] DROP CONSTRAINT [FK_confirmados_laboratorio]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_confirmados_paciente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [confirmados] DROP CONSTRAINT [FK_confirmados_paciente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_dosis_paciente_centro_vacunacion]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [dosis_paciente] DROP CONSTRAINT [FK_dosis_paciente_centro_vacunacion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_dosis_paciente_fabricante_vacuna]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [dosis_paciente] DROP CONSTRAINT [FK_dosis_paciente_fabricante_vacuna]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_dosis_paciente_paciente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [dosis_paciente] DROP CONSTRAINT [FK_dosis_paciente_paciente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_enfermedad_base_paciente_enfermedad_base]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [enfermedades_base_paciente] DROP CONSTRAINT [FK_enfermedad_base_paciente_enfermedad_base]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_enfermedad_base_paciente_paciente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [enfermedades_base_paciente] DROP CONSTRAINT [FK_enfermedad_base_paciente_paciente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_evaluacion_estado]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [evaluacion] DROP CONSTRAINT [FK_evaluacion_estado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_evaluacion_paciente]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [evaluacion] DROP CONSTRAINT [FK_evaluacion_paciente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_evaluacion_tipo_caso]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [evaluacion] DROP CONSTRAINT [FK_evaluacion_tipo_caso]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_evaluacion_usuario]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [evaluacion] DROP CONSTRAINT [FK_evaluacion_usuario]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_paciente_colonias]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [paciente] DROP CONSTRAINT [FK_paciente_colonias]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_sintoma_gravedad_sintoma]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [sintoma] DROP CONSTRAINT [FK_sintoma_gravedad_sintoma]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_sintomas_evaluacion_evaluacion]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [sintomas_evaluacion] DROP CONSTRAINT [FK_sintomas_evaluacion_evaluacion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_sintomas_evaluacion_sintoma]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [sintomas_evaluacion] DROP CONSTRAINT [FK_sintomas_evaluacion_sintoma]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_usuario_rol]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [usuario] DROP CONSTRAINT [FK_usuario_rol]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_usuario_tipo_documento]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [usuario] DROP CONSTRAINT [FK_usuario_tipo_documento]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[centro_vacunacion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [centro_vacunacion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[colonias]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [colonias]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[confirmados]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [confirmados]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[dosis_paciente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [dosis_paciente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[enfermedad_base]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [enfermedad_base]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[enfermedades_base_paciente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [enfermedades_base_paciente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[estado]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [estado]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[evaluacion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [evaluacion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[fabricante_vacuna]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [fabricante_vacuna]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[gravedad_sintoma]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [gravedad_sintoma]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[laboratorio]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [laboratorio]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[paciente]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [paciente]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[rol]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [rol]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[sintoma]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [sintoma]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[sintomas_evaluacion]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [sintomas_evaluacion]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[tipo_caso]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [tipo_caso]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[tipo_documento]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [tipo_documento]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[usuario]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [usuario]
GO

/* Create Tables */

CREATE TABLE [centro_vacunacion]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[nombre] varchar(50) NOT NULL,
	[direccion] varchar(150) NOT NULL
)
GO

CREATE TABLE [colonias]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[nombre] varchar(50) NOT NULL,
	[activo] bit NOT NULL
)
GO

CREATE TABLE [confirmados]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[id_paciente] int NOT NULL,
	[id_laboratorio] int NOT NULL,
	[fecha_examen] datetime NOT NULL,
	[fecha_entrega_resultado] datetime NOT NULL,
	[fecha_recuperacion] date NULL,
	[fecha_deceso] date NULL,
	[recuperado] bit NOT NULL,
	[fallecido] bit NOT NULL
)
GO

CREATE TABLE [dosis_paciente]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[id_centro_vacunacion] int NULL,
	[id_paciente] int NOT NULL,
	[id_fabricante] int NOT NULL,
	[lote] varchar(50) NOT NULL,
	[fecha] date NOT NULL
)
GO

CREATE TABLE [enfermedad_base]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[nombre] varchar(50) NOT NULL,
	[activo] bit NOT NULL
)
GO

CREATE TABLE [enfermedades_base_paciente]
(
	[id] int NOT NULL,
	[id_paciente] int NOT NULL,
	[id_enfermedad_base] int NOT NULL
)
GO

CREATE TABLE [estado]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[nombre] varchar(25) NOT NULL,
	[descripcion] varchar(100) NULL
)
GO

CREATE TABLE [evaluacion]
(
	[id_evaluacion] int NOT NULL IDENTITY (1, 1),
	[id_usuario] int NOT NULL,
	[id_paciente] int NOT NULL,
	[id_estado] int NOT NULL,
	[id_tipo_caso] int NOT NULL,
	[fecha_hora] datetime NOT NULL,
	[comentarios] varchar(250) NULL
)
GO

CREATE TABLE [fabricante_vacuna]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[nombre] varchar(50) NOT NULL
)
GO

CREATE TABLE [gravedad_sintoma]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[gravedad] varchar(25) NOT NULL,
	[descripcion] varchar(50) NOT NULL
)
GO

CREATE TABLE [laboratorio]
(
	[id] int NOT NULL,
	[nombre] varchar(50) NOT NULL,
	[direccion] varchar(150) NOT NULL
)
GO

CREATE TABLE [paciente]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[id_tipo_documento] int NOT NULL,
	[id_colonia] int NOT NULL,
	[nombre] varchar(50) NOT NULL,
	[apellido] varchar(50) NOT NULL,
	[direccion] varchar(150) NOT NULL,
	[telefono] varchar(12) NOT NULL,
	[fecha_nacimiento] date NOT NULL,
	[documento] varchar(50) NOT NULL,
	[correo] varchar(50) NULL
)
GO

CREATE TABLE [rol]
(
	[id] int NOT NULL,
	[nombre] varchar(50) NOT NULL,
	[descripcion] varchar(100) NULL
)
GO

CREATE TABLE [sintoma]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[id_gravedad_sintoma] int NOT NULL,
	[sintoma] varchar(50) NOT NULL
)
GO

CREATE TABLE [sintomas_evaluacion]
(
	[id] int NOT NULL,
	[id_evaluacion] int NOT NULL,
	[id_sintoma] int NOT NULL
)
GO

CREATE TABLE [tipo_caso]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[tipo] varchar(50) NOT NULL
)
GO

CREATE TABLE [tipo_documento]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[nombre_tipo_documento] varchar(50) NOT NULL
)
GO

CREATE TABLE [usuario]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[id_tipo_documento] int NOT NULL,
	[id_rol] int NOT NULL,
	[nombre] varchar(50) NOT NULL,
	[apellido] varchar(50) NOT NULL,
	[correo] varchar(50) NOT NULL,
	[direccion] varchar(150) NOT NULL,
	[telefono] varchar(10) NOT NULL,
	[fecha_nacimiento] date NOT NULL,
	[documento] varchar(25) NOT NULL,
	[nombre_usuario] varchar(30) NOT NULL,
	[contrasena] varchar(100) NOT NULL,
	[fecha_cambio_contrasena] datetime NOT NULL,
	[activo] bit NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [centro_vacunacion] 
 ADD CONSTRAINT [PK_centro_vacunacion]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [colonias] 
 ADD CONSTRAINT [PK_colonias]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [confirmados] 
 ADD CONSTRAINT [PK_confirmados]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [dosis_paciente] 
 ADD CONSTRAINT [PK_dosis_paciente]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [enfermedad_base] 
 ADD CONSTRAINT [PK_enfermedad_base]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [enfermedades_base_paciente] 
 ADD CONSTRAINT [PK_enfermedad_base_paciente]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [estado] 
 ADD CONSTRAINT [PK_estado]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [evaluacion] 
 ADD CONSTRAINT [PK_evaluacion]
	PRIMARY KEY CLUSTERED ([id_evaluacion] ASC)
GO

ALTER TABLE [fabricante_vacuna] 
 ADD CONSTRAINT [PK_fabricante_vacuna]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [gravedad_sintoma] 
 ADD CONSTRAINT [PK_gravedad_sintoma]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [laboratorio] 
 ADD CONSTRAINT [PK_laboratorio]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [paciente] 
 ADD CONSTRAINT [PK_paciente]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [rol] 
 ADD CONSTRAINT [PK_rol]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [sintoma] 
 ADD CONSTRAINT [PK_sintoma]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [sintomas_evaluacion] 
 ADD CONSTRAINT [PK_sintomas_evaluacion]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [tipo_caso] 
 ADD CONSTRAINT [PK_tipo_caso]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [tipo_documento] 
 ADD CONSTRAINT [PK_tipo_documento]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [usuario] 
 ADD CONSTRAINT [PK_usuarios]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [confirmados] ADD CONSTRAINT [FK_confirmados_laboratorio]
	FOREIGN KEY ([id_laboratorio]) REFERENCES [laboratorio] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [confirmados] ADD CONSTRAINT [FK_confirmados_paciente]
	FOREIGN KEY ([id_paciente]) REFERENCES [paciente] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dosis_paciente] ADD CONSTRAINT [FK_dosis_paciente_centro_vacunacion]
	FOREIGN KEY ([id_centro_vacunacion]) REFERENCES [centro_vacunacion] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dosis_paciente] ADD CONSTRAINT [FK_dosis_paciente_fabricante_vacuna]
	FOREIGN KEY ([id_fabricante]) REFERENCES [fabricante_vacuna] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [dosis_paciente] ADD CONSTRAINT [FK_dosis_paciente_paciente]
	FOREIGN KEY ([id_paciente]) REFERENCES [paciente] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [enfermedades_base_paciente] ADD CONSTRAINT [FK_enfermedad_base_paciente_enfermedad_base]
	FOREIGN KEY ([id_enfermedad_base]) REFERENCES [enfermedad_base] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [enfermedades_base_paciente] ADD CONSTRAINT [FK_enfermedad_base_paciente_paciente]
	FOREIGN KEY ([id_paciente]) REFERENCES [paciente] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [evaluacion] ADD CONSTRAINT [FK_evaluacion_estado]
	FOREIGN KEY ([id_estado]) REFERENCES [estado] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [evaluacion] ADD CONSTRAINT [FK_evaluacion_paciente]
	FOREIGN KEY ([id_paciente]) REFERENCES [paciente] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [evaluacion] ADD CONSTRAINT [FK_evaluacion_tipo_caso]
	FOREIGN KEY ([id_tipo_caso]) REFERENCES [tipo_caso] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [evaluacion] ADD CONSTRAINT [FK_evaluacion_usuario]
	FOREIGN KEY ([id_usuario]) REFERENCES [usuario] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [paciente] ADD CONSTRAINT [FK_paciente_colonias]
	FOREIGN KEY ([id_colonia]) REFERENCES [colonias] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [sintoma] ADD CONSTRAINT [FK_sintoma_gravedad_sintoma]
	FOREIGN KEY ([id_gravedad_sintoma]) REFERENCES [gravedad_sintoma] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [sintomas_evaluacion] ADD CONSTRAINT [FK_sintomas_evaluacion_evaluacion]
	FOREIGN KEY ([id_evaluacion]) REFERENCES [evaluacion] ([id_evaluacion]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [sintomas_evaluacion] ADD CONSTRAINT [FK_sintomas_evaluacion_sintoma]
	FOREIGN KEY ([id_sintoma]) REFERENCES [sintoma] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [usuario] ADD CONSTRAINT [FK_usuario_rol]
	FOREIGN KEY ([id_rol]) REFERENCES [rol] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [usuario] ADD CONSTRAINT [FK_usuario_tipo_documento]
	FOREIGN KEY ([id_tipo_documento]) REFERENCES [tipo_documento] ([id]) ON DELETE No Action ON UPDATE No Action
GO
